version: '3.0'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main/main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db

  admin-queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    environment:
      DJANGO_SETTINGS_MODULE: admin.settings
    volumes:
      - .:/app
    depends_on:
      - db

  main-queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main/consumer.py'
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: admin
    volumes:
      - .dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
